module.exports = Object.freeze({
  schemaVersion: 2,
  platform: 'web',
  hostingProviders: Object.freeze({
    githubDotCom: Object.freeze({
      authentication: 'personal-access-token',
      status: 'unavailable',
    }),
    githubEnterprise: Object.freeze({
      authentication: 'personal-access-token',
      status: 'unavailable',
    }),
    bitbucket: Object.freeze({ status: 'unavailable' }),
    gitlab: Object.freeze({
      authentication: 'personal-access-token',
      status: 'unavailable',
    }),
    forgejo: Object.freeze({ status: 'unavailable' }),
    gitea: Object.freeze({ status: 'unavailable' }),
  }),
  features: Object.freeze({
    localRepositories: 'supported',
    history: 'supported',
    changesAndCommits: 'supported',
    branchesAndTags: 'supported',
    repositoryListIndicators: 'supported',
    repositoryRecovery: 'supported',
    updateFromDefaultBranch: 'supported',
    stashes: 'supported',
    worktrees: 'supported',
    advancedHistoryRewrites: 'supported',
    inProgressGitOperations: 'supported',
    pullRequests: 'unavailable',
    hostingAuthentication: 'unavailable',
    editorIntegration: 'partial',
    shellIntegration: 'partial',
    filesystemIntegration: 'partial',
    browserNotifications: 'supported',
    nativeNotifications: 'unavailable',
    automaticUpdates: 'partial',
    copilot: 'unavailable',
    pushProtectionBypass: 'unavailable',
    repositoryRules: 'unavailable',
    globalLfsInstall: 'partial',
    gitLfs: 'partial',
  }),
})
